const PDFDocument = require('pdfkit');

async function generateReport(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const patient = report.patientId;
    const scan    = report.scanId;
    const W       = doc.page.width;

    doc.rect(0, 0, W, 90).fill('#1A3C5E');
    doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold')
       .text('EyeAI Diagnostics', 50, 22);
    doc.fontSize(10).font('Helvetica')
       .text('Advanced Ocular Disease Detection Platform', 50, 50);
    doc.text(`Report ID: ${report._id}`, 50, 65);
    doc.fillColor('#000000');

    doc.moveDown(4);

    sectionTitle(doc, 'Patient Information');
    const pi = patient || {};
    infoRow(doc, 'Full Name',   pi.name || 'N/A');
    infoRow(doc, 'Patient ID',  pi.patientId || 'N/A');
    infoRow(doc, 'Age',         pi.age ? `${pi.age} years` : 'N/A');
    infoRow(doc, 'Gender',      pi.gender || 'N/A');
    infoRow(doc, 'Exam Date',   scan?.examDate ? new Date(scan.examDate).toLocaleDateString() : new Date().toLocaleDateString());
    infoRow(doc, 'Clinician',   scan?.clinicianName || 'N/A');
    doc.moveDown();

    sectionTitle(doc, 'Diagnostic Results');

    for (const result of report.results || []) {
      const isPositive = result.prediction !== 'Normal';
      const color = isPositive ? '#C0392B' : '#27AE60';

      doc.fontSize(13).font('Helvetica-Bold').fillColor('#1A3C5E')
         .text(result.disease, { continued: true });
      doc.fontSize(12).font('Helvetica-Bold').fillColor(color)
         .text(`  ➜  ${result.prediction}  (${(result.confidence * 100).toFixed(1)}% confidence)`);
      doc.fillColor('#000000');

      if (result.probabilities) {
        for (const [label, prob] of Object.entries(result.probabilities)) {
          const pct = (prob * 100).toFixed(1);
          doc.fontSize(9).font('Helvetica').text(`  ${label}: ${pct}%`);
        }
      }

      if (result.gradcam) {
        try {
          const imgBuffer = Buffer.from(result.gradcam, 'base64');
          doc.image(imgBuffer, { width: 200, align: 'center' });
          doc.fontSize(8).fillColor('#555').text('Grad-CAM attention heatmap', { align: 'center' });
          doc.fillColor('#000000');
        } catch (_) {  }
      }

      doc.moveDown();
    }

    if (report.doctorNotes) {
      sectionTitle(doc, 'Clinician Notes');
      doc.fontSize(11).font('Helvetica').text(report.doctorNotes);
      doc.moveDown();
    }

    sectionTitle(doc, 'General Eye Care Recommendations');
    const tips = [
      'Schedule a comprehensive eye exam with a specialist as follow-up.',
      'Maintain blood sugar and blood pressure within normal ranges.',
      'Wear UV-protective eyewear when outdoors.',
      'Report any sudden changes in vision immediately to a clinician.',
    ];
    tips.forEach((tip) => {
      doc.fontSize(10).font('Helvetica').text(`• ${tip}`);
    });

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888')
       .text('This report is generated by EyeAI Diagnostics and is intended as a decision-support tool only. It does not replace professional clinical judgment.', {
         align: 'center',
       });

    doc.end();
  });
}

function sectionTitle(doc, title) {
  doc.moveDown(0.5);
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#1A3C5E').text(title);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1A3C5E').stroke();
  doc.moveDown(0.3).fillColor('#000000');
}

function infoRow(doc, label, value) {
  doc.fontSize(11).font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(value);
}

module.exports = { generateReport };
